### ISSUE TITLE
Redesign: EditText hint should get cleared when clicked in Edit Profile

### ISSUE THREAD

**Issue by codepoet2017390** [openMF/mobile-wallet#290]
**Summary:**

EditText hint should get cleared when the textBox is clicked in Edit Profile.

**Steps to reproduce:**

1. Open app in redesign and go to Edit Profile
2. Click on any Edit Text textbox.
3. Text hint should be automatically cleared.

**Device and Android version:**

OnePlus5 Android 9(Pie)

**Comment by shaliniv16** [comment]
@codepoet2017390 Can I work on it?

**Comment by codepoet2017390** [comment]
I am working on it

**Comment by letelete** [comment]
This is an intended action. 

We don't want to clear the input on click since that would be really annoying for the user whenever he would want to change anything, he had to type all data manually.

The purposes of those hints are:

* making changes readable and noticeable for the user
* making edit actions very easy, which is important since we don't want user to do any mistakes

As you might see on the gif, every not-edited edit text gets its own hint, however edited one stays with text inside.

![ezgif-1-fde68c86e025](https://user-images.githubusercontent.com/18665370/52911176-9e176400-32a0-11e9-8dc5-47cd6dbb27f3.gif)

**Comment by codepoet2017390** [comment]
@letelete  Yes ur right, this behavior seems right
