### ISSUE TITLE
Amount column in Transfer fragment can accept .(dot or decimal) as amount.

### ISSUE THREAD

**Issue by shaliniv16** [openMF/mobile-wallet#315]
**Summary:**

Amount column in Transfer fragment can accept .(dot or decimal) as amount. It can attain decimal value.

**Device and Android version:**

Realme 2 Pro
Android version 8.1.0

**Comment by shaliniv16** [comment]
@luckyman20 Can I work on it?

**Comment by luckyman20** [comment]
It should.

**Comment by shaliniv16** [comment]
@luckyman20 Why did you close this issue?

**Comment by luckyman20** [comment]
@shaliniv16 What we can alternatively do is that we would accept upto 2 decimal digits only. Make a new issue regarding that.

Why I closed this issue - Let me explain a use case for this, suppose a user has Rs. 50.25 in his account because of different discount/cashback policy and now the user wants to close the account, so he/she want to transfer this money to some other account, in this case, we need accept (.) decimals too.

**Comment by shaliniv16** [comment]
@luckyman20 Can I make a new issue regarding 2 decimal digits only?
