### ISSUE TITLE
Add account button not working in dev_redesign 

### ISSUE THREAD

**Issue by Vipinsoni38** [openMF/mobile-wallet#501]
add account in finance section is not working
![20190319_131023_rmscr](https://user-images.githubusercontent.com/32003964/54588380-d4cfce00-4a48-11e9-85e9-2f40080117a9.jpg)

**Comment by shaliniv16** [comment]
@Vipinsoni38 this issue is resolved in Dev branch.

**Comment by Vipinsoni38** [comment]
Adding these Features will simplify the process 
almost everything of branch redesign is resolved in Dev
So just trying to smoothen the process :)

**Comment by RajaVamsi11** [comment]
@Vipinsoni38 The redesign branch is only for UI purpose. As @shaliniv16 told that implementing features that exist in dev branch does not make sense. The mentors will make decisions to add features in the redesign branch.  Minor UI issues can be solved in redesign branch rather than adding features that are already implemented in other branches. Hope you understand.

**Comment by Vipinsoni38** [comment]
hmm ohk got it! 
thnx @RajaVamsi11
